baseURL = "https://archphile.org"
title = "Archphile"
theme = "manis"

# Copyright notice. Note: You can use HTML tag here
copyright = "Copyleft 2014 - âˆž | M. A."
pluralizeListTitles = true 

# Minimum number of posts before paginate navigation show up
paginate = 10

# Your disqus shortname
#disqusShortname = ""

# Edit this if you want to translate your blog
defaultContentLanguage = "en"

# Code Highlighting (Chroma)
pygmentsCodeFences = true
pygmentsUseClasses = true

[taxonomies]
	tag = "tags"

[params]
	# If false, use minified CSS (ui.min.css)
	debugCSS = false
	# Custom CSS
	customCSS = []
	
	# List of sections support disqus comments
        # disqusSections = [ "blog" ]
	# Site meta description
	description = "Archphile - yet another linux audio distribution for embedded boards"
	# Site's Tagline (Subtitle or Keyword)
	tagline = "yet another linux audio distribution for embedded boards"
	# If true give attribution to this theme
	themeAttrib = false
	# URL to license file, can be outside of your domain
	# licenseURL = "/about/license"

	# Configure which section for Latest Posts
	postSection = "blog"
	
	# 404 Configuration
	head404 = "Sorry, I can't find what you want."
	sub404 = "Back to <a href='/'>Home</a>."

	# Color of your website's accent
	colorTheme = "#43c3e7"
	# Maximum number of item in Latest Posts or Works
	latestCount = 3
	# Path to site's favicon image
	faviconImg = "/img/favicon.ico"
	# Date format in item list
	dateFmt = "Jan 02, 2006"

	# Code Highlighting (HighlightJS)
	highlightJs = true
	highlightJsLanguages = [ "go" ]
	highlightJsStyle = "ocean"

	# Social Links
	email = "info@archphile.org"
	github = "https://github.com/archphile"


# Language Configuration
#[languages.in]
#	lang = "in"
#	languageName = "Bahasa Indonesia"
#	weight = 1